Fix for when script is invoked thru symbolic link (commonly symlinked in /etc/cron.daily).
git-svn-id: svn+ssh://svn.bmc.uu.se/cbe/openexam-php/trunk@2356 58b8aac4-d633-40de-91bf-eab09b0297ab

diff --git a/version2/admin/crontab/openexam-result.sh.in b/version2/admin/crontab/openexam-result.sh.in
--- a/version2/admin/crontab/openexam-result.sh.in
+++ b/version2/admin/crontab/openexam-result.sh.in
@@ -6,8 +6,8 @@
 # Author: Anders Lövgren
 # Date:   2016-04-20
 
-# Current directory:
-cwd="$(dirname $0)"
+# This script directory:
+cwd="$(dirname $(realpath $0))"
 
 # The phalcon directory:
 root="$(realpath $cwd/../../phalcon-mvc)"
@@ -19,15 +19,19 @@ user="apache"
 script="$root/script/openexam.php"
 
 # Extra options:
-#options="--verbose"
+#options="--verbose --force"
 
 if ! [ -e $script ]; then
   echo "$0: missing script $script"
   exit 1
 fi
+if ! [ -d $root ]; then
+  echo "$0: missing application directory $root"
+  exit 1
+fi
 
 # Cleanup old result files:
-sudo -u $user /usr/bin/php $script --result --delete --days=30 $options $*
+/usr/bin/sudo -u $user /usr/bin/php $script --result --delete --days=90 $options $*
 
 # Generate new result files:
-sudo -u $user /usr/bin/php $script --result --create --days=14 $options $*
+/usr/bin/sudo -u $user /usr/bin/php $script --result --create --days=30 $options $*
