Use lockfile to prevent concurrent jobs from multiple host or same job running twice (possibly overwriting its own results).
git-svn-id: svn+ssh://svn.bmc.uu.se/cbe/openexam-php/trunk@3096 58b8aac4-d633-40de-91bf-eab09b0297ab

diff --git a/admin/crontab/openexam-archive.sh.in b/admin/crontab/openexam-archive.sh.in
--- a/admin/crontab/openexam-archive.sh.in
+++ b/admin/crontab/openexam-archive.sh.in
@@ -12,6 +12,9 @@ cwd="$(dirname $(realpath $0))"
 # The phalcon directory:
 root="$(realpath $cwd/../../phalcon-mvc)"
 
+# Lock file for cron job:
+lock="$cwd/cache/archive.lock"
+
 # Web server user:
 user="apache"
 
@@ -29,6 +32,13 @@ if ! [ -d $root ]; then
   echo "$0: missing application directory $root"
   exit 1
 fi
+if [ -e $lock ]; then
+  echo "$0: lock file exist (previous job not finished?)"
+  exit 1
+fi
+
+# Create lock file:
+touch $lock
 
 # Create new archives:
 /usr/bin/sudo -u $user /usr/bin/php $script --archive --create --all --quiet $options $*
@@ -38,3 +48,6 @@ fi
 
 # Find exams not being archived:
 /usr/bin/sudo -u $user /usr/bin/php $script --archive --missing $options $*
+
+# Cleanup lock file:
+rm -f $lock
diff --git a/admin/crontab/openexam-audit.sh.in b/admin/crontab/openexam-audit.sh.in
--- a/admin/crontab/openexam-audit.sh.in
+++ b/admin/crontab/openexam-audit.sh.in
@@ -11,6 +11,9 @@ cwd="$(dirname $(realpath $0))"
 # The phalcon directory:
 root="$(realpath $cwd/../../phalcon-mvc)"
 
+# Lock file for cron job:
+lock="$cwd/cache/audit.lock"
+
 # Web server user:
 user="apache"
 
@@ -28,6 +31,16 @@ if ! [ -d $root ]; then
   echo "$0: missing application directory $root"
   exit 1
 fi
+if [ -e $lock ]; then
+  echo "$0: lock file exist (previous job not finished?)"
+  exit 1
+fi
+
+# Create lock file:
+touch $lock
 
 # Cleanup expired audit data:
 /usr/bin/sudo -u $user /usr/bin/php $script --audit --clean --days=90 $options $*
+
+# Cleanup lock file:
+rm -f $lock
diff --git a/admin/crontab/openexam-result.sh.in b/admin/crontab/openexam-result.sh.in
--- a/admin/crontab/openexam-result.sh.in
+++ b/admin/crontab/openexam-result.sh.in
@@ -12,6 +12,9 @@ cwd="$(dirname $(realpath $0))"
 # The phalcon directory:
 root="$(realpath $cwd/../../phalcon-mvc)"
 
+# Lock file for cron job:
+lock="$cwd/cache/result.lock"
+
 # Web server user:
 user="apache"
 
@@ -29,9 +32,19 @@ if ! [ -d $root ]; then
   echo "$0: missing application directory $root"
   exit 1
 fi
+if [ -e $lock ]; then
+  echo "$0: lock file exist (previous job not finished?)"
+  exit 1
+fi
+
+# Create lock file:
+touch $lock
 
 # Cleanup old result files:
 /usr/bin/sudo -u $user /usr/bin/php $script --result --delete --days=90 $options $*
 
 # Generate new result files:
 /usr/bin/sudo -u $user /usr/bin/php $script --result --create --days=30 $options $*
+
+# Cleanup lock file:
+rm -f $lock
